// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://dqeaatpqbqjdpgdtyqfv.supabase.co";
const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxZWFhdHBxYnFqZHBnZHR5cWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0MDU1NTcsImV4cCI6MjA0OTk4MTU1N30.fCqnHgpJWX3c5-iNzfJHdLXWHDuOp3Xsm3Bj_kH-pLs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    storageKey: 'morvo-auth-token',
    storage: window.localStorage,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'X-Client-Info': 'morvo-ai-frontend'
    }
  },
  db: {
    schema: 'public'
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});